<?php

// Test (justo to save the html generated by render)

$result[] = array('id_profile' => 13,
                'id_product' => 17,
                'views' => 12,
                'name' => 'cool product',
                'description' => 'I am a natural fake product just made by silly people.',
                'price' => '22.3',
                'sale' => '',
                'fullprice' => '40.0',
                'category' => 'apple',
                'username' => 'pippo',
                'area' => 'bolzano',
                'date' => '20/05/2016',
                'quantity' => 100,
                'rating' => '3');

echo json_encode($result);